# Generated by Django 5.1.6 on 2025-02-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_in_stock_product_is_top_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/%Y/%m/%d', verbose_name='Image2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/%Y/%m/%d', verbose_name='Image3'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/%Y/%m/%d', verbose_name='Image4'),
        ),
    ]
